# Generated by Django 2.0 on 2020-07-05 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image_rep', models.ImageField(blank=True, max_length=255, null=True, upload_to='class')),
            ],
        ),
        migrations.CreateModel(
            name='Image_class_picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_picture', models.ImageField(blank=True, max_length=255, null=True, upload_to='classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Image_Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_Class', models.ImageField(blank=True, max_length=255, null=True, upload_to='classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Image_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, null=True, upload_to='image')),
                ('class_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appimage.Class_User')),
            ],
        ),
    ]
